apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-alm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-alm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi